# Generated by Django 4.0.3 on 2022-04-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='date_done',
            field=models.DateTimeField(auto_now=True, verbose_name='date done'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='mark_done',
            field=models.BooleanField(default=False, verbose_name='mark done'),
        ),
    ]
