# Generated by Django 4.0.3 on 2022-03-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='type',
            field=models.CharField(choices=[('ELECTRICIAN', 'Electrician'), ('CARPENTER', 'Carpenter'), ('CLEANER', 'Cleaner'), ('PLUMBER', 'Plumber'), ('OTHERS', 'Others')], max_length=100, verbose_name='type'),
        ),
    ]
