# Generated by Django 4.0.3 on 2022-03-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_complaint_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hostel',
        ),
        migrations.AddField(
            model_name='user',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='roll number'),
        ),
    ]
