# Generated by Django 4.0.3 on 2022-04-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_hostel_user_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='roll number'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='room number'),
        ),
    ]
