# Generated by Django 4.0.3 on 2022-04-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_complaint_roll_number_complaint_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='worker',
        ),
        migrations.AddField(
            model_name='complaint',
            name='contact_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='contact number'),
        ),
    ]
